name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Create package
        working-directory: src\Arena\Package
        shell: pwsh
        run: .\Create-Package.ps1

      - uses: actions/upload-artifact@v3
        with:
          name: arena
          path: src\Arena\Package\Arena.zip
          if-no-files-found: error
